### ISSUE TITLE
Ruby 1.8.7 fails to build in travis

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-puppet#118]
We started getting this rather obscure error message on on PRs. I then re-ran the master branch which had previously been all green lights, but then started getting this same error there too. Only seems to be an issue for ruby 1.8.7.

```
/home/travis/.rvm/rubies/ruby-1.8.7-p374/bin/ruby -I/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib:/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-support-3.2.2/lib /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
/home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:512:in `all_hooks_for': return from proc-closure (LocalJumpError)
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:564:in `process'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/flat_map.rb:11:in `map'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/flat_map.rb:11:in `flat_map'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:563:in `process'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:429:in `register_globals'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:394:in `set_it_up'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:361:in `subclass'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:253:in `describe'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/dsl.rb:43:in `__send__'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/dsl.rb:43:in `describe'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/dsl.rb:82:in `__send__'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/dsl.rb:82:in `describe'
from /home/travis/build/lightblue-platform/lightblue-puppet/spec/classes/lightblue/application/datamgmt_spec.rb:3
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1226:in `load'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1224:in `each'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:97:in `setup'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:85:in `run'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:70:in `run'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:38:in `invoke'
from /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rspec-core-3.2.2/exe/rspec:4
```

**Comment by dcrissman** [comment]
I found a couple complaints about a similar sounding issue from others, in both cases they decided to abandon 1.8.7 altogether.
* https://github.com/dfarrell07/puppet-opendaylight/issues/33
* https://github.com/rspec/rspec-core/issues/1864
  * good explanation of problem, believes it has something to do with a mokeypatch.

**Comment by dcrissman** [comment]
#114, #116, and #117 are all currently blocked by this issue.

**Comment by jewzaam** [comment]
Talked with @dcrissman and we're going to recommend removing ruby 1.8.7 from our builds for now (PR coming soon).  Our puppet runs internally are not having problems.  Tagging this issue for the Bill release.
