### ISSUE TITLE
migrator: puppetize log4j configuration

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-puppet#121]
This would be a follow up to https://github.com/lightblue-platform/lightblue-migrator/issues/111

**Comment by dcrissman** [comment]
-Dlog4j.configuration=file:/path/log4j.properties

**Comment by dcrissman** [comment]
log4j is easily able to handle log rotation and limiting the number of logs to keep, see the below example.

```
log4j.rootLogger=<%= @log_level %>,file

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=<%= @log_file %>
log4j.appender.file.MaxFileSize=<%= @log_max_file_size %>
log4j.appender.file.MaxBackupIndex=<%= @log_max_backups_to_keep %>
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d [%t] %c %p - %m%n
```

**Comment by dcrissman** [comment]
As it is today, the migrator (using jsvc under the hood) logs all stdout/stderr output to whatever file path is assigned to *lightblue::application::migrator::service_log_file*. The embedded <a href="https://github.com/lightblue-platform/lightblue-migrator/blob/master/consistency-checker/src/main/resources/log4j.properties">log4j.properties</a> file in the migrator code base is used by default and simply prints everything to console, ergo, log4j does not actually control the log file and all logs from either jsvc itself and the migrator application will end up there.

If you want to rotate logs or separate jsvc logs from application logs a customer log4j.properties file will need to be written. You can use the earlier example or write your own.

Here is how you would configure puppet to apply the custom log4j,properties.
```yaml
lightblue::application::migrator::serviceJvmOptions:
    - Dlog4j.configuration=file:/path/to/log4j.properties
```

**Comment by dcrissman** [comment]
Not quite ready to make a PR yet, but made some significant progress. This turned out to be a fairly large refactor, not because the work is hard, but rather to make it all consistent. I have the migrator deploying and running, but I am getting an exception that I'll have to pick up next week.

```
Caused by: java.security.KeyStoreException: Cannot store non-PrivateKeys
	at sun.security.provider.JavaKeyStore.engineSetKeyEntry(JavaKeyStore.java:250)
	at sun.security.provider.JavaKeyStore$JKS.engineSetKeyEntry(JavaKeyStore.java:55)
	at java.security.KeyStore.setKeyEntry(KeyStore.java:909)
	at com.redhat.lightblue.client.http.auth.SslSocketFactories.getJksKeyStore(SslSocketFactories.java:128)
	at com.redhat.lightblue.client.http.auth.SslSocketFactories.defaultCertAuthSocketFactory(SslSocketFactories.java:97)
	at com.redhat.lightblue.client.http.auth.HttpClientCertAuth.<init>(HttpClientCertAuth.java:57)
	... 54 more
```

**Comment by dcrissman** [comment]
PR #122 submitted to fix this issue.
